/** @type {import('tailwindcss').Config} */
// Design tokens copied verbatim from the supplied "Clinical Precision" template
// (UIUX Design/s2, s5, s17 code.html) - see docs/UIUX.md §1.
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#273143",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#141b2b",
        "surface-container-low": "#f0f3ff",
        "inverse-on-surface": "#ecf0ff",
        "on-primary-container": "#fefcff",
        surface: "#f9f9ff",
        "on-tertiary-fixed-variant": "#404758",
        "secondary-container": "#316bf3",
        "on-surface": "#111c2d",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c0c6db",
        "surface-bright": "#f9f9ff",
        "surface-container-highest": "#d9e3fb",
        outline: "#727785",
        "surface-tint": "#005ac2",
        "on-secondary-fixed": "#00174b",
        "on-secondary-container": "#fefcff",
        "on-error": "#ffffff",
        "surface-dim": "#d0daf2",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-high": "#dfe8ff",
        tertiary: "#555c6e",
        "on-primary-fixed-variant": "#004395",
        "on-primary-fixed": "#001a42",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fefcff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#003ea8",
        "tertiary-container": "#6e7487",
        "inverse-primary": "#adc6ff",
        "primary-fixed": "#d8e2ff",
        background: "#f9f9ff",
        "on-surface-variant": "#424754",
        primary: "#0058be",
        "on-background": "#111c2d",
        "surface-variant": "#d9e3fb",
        "primary-container": "#2170e4",
        "outline-variant": "#c2c6d6",
        error: "#ba1a1a",
        "surface-container": "#e8eeff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed": "#dbe1ff",
        "tertiary-fixed": "#dce2f7",
        secondary: "#0051d5",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "2xl": "20px",
      },
      spacing: {
        "stack-lg": "48px",
        "margin-desktop": "40px",
        "stack-sm": "12px",
        "margin-mobile": "16px",
        "stack-md": "24px",
        gutter: "24px",
        base: "8px",
        "container-max": "1440px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-kpi": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "display-kpi": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
